ProblematicDevelopers/pullit-frontend

package-lock.json, package.json, src/App.vue, src/components/ApiTest.vue, src/components/statistics/StatisticsTest.vue, src/main.js, src/router/index.js
closes #4 
---
router 추가 
---
---
---
---
=> feat:router 추가

src/App.vue, src/Home.vue, src/assets/styles/wizard.css, src/components/WizardComponent.vue, src/components/wizard/Step0SelectMode.vue, src/components/wizard/Step1UnitSelection.vue, src/components/wizard/WizardHeader.vue, src/main.js, src/router/index.js, src/stores/testBank.js, src/utils/popup.js, src/views/HomeView.vue, src/views/TestWizardView.vue
=> feat : examWizard 생성

src/components/student/Main.vue
=> hotfix: 오류수정

src/components/common/subjects/ChapterList.vue, src/components/student/cbt/CBTStep01.vue, src/store/chapterStore.js
closes #18 
---
챕터 목록을 불러오는 컴포넌트 추가
---
---
---
---
=> feat: 챕터 리스트 추가

src/App.vue, src/components/common/Header.vue, src/components/common/WizardModal.vue, src/components/wizard/Step0SelectMode.vue, src/components/wizard/Step1UnitSelection.vue, src/router/index.js, src/services/examApi.js, src/stores/testBank.js, src/views/MainDashboard.vue, src/views/TestWizardView.vue
closes #23 
---
---
---
---
---
=> feat: testWizard 검색기능 추가

src/services/itemApi.js
=> feat: Wrapping

src/components/wizard/Step2ItemSelection.vue, src/services/itemApi.js, src/stores/itemSelection.js
=> hotfix: ES

src/components/common/subjects/TextbookList.vue, src/router/index.js, src/store/itemProcessingStore.js, src/store/textbookStore.js, src/views/ItemProcessing.vue, src/views/ItemProcessingTextbook.vue
closes #48 
---
문제등록 첫페이지 변경(문제유형 -> 교과서선택) 및 추가
---
---
---
---
=> feat: 문제등록 (유형 선택 -> 교과서 선택)으로 페이지 변경 및 추가

src/services/api.js, src/store/itemProcessingStore.js
closes #51 
---
문제가공 페이지 내 api 관련 호출 api.js로 관리하도록수정
---
---
---
---
=> fix: api 호출관련 api.js로 처리하도록 변경

package-lock.json, package.json, src/components/wizard/Step0SelectMode.vue, src/components/wizard/Step2ItemSelection.vue, src/stores/testBank.js
closes #53 
---
---
---
---
---
=> feat: PDFME 종속성 추가

src/components/student/Main.vue, src/components/student/report/QuestionHtmlModal.vue, src/components/student/report/ReportList.vue
closes #79 
---
fix:student main 문구 수정, 문제상세보기 수정
---
---
---
---
=> fix:student main 문구 수정, 문제상세보기 수정

src/services/pdfGenerator.js
=> hotfix: error

src/components/student/report/BasicReport.vue
=> add:basicreport 뒤로가기 추가

src/components/student/report/BasicReport.vue, src/components/student/report/ChartComponent.vue, src/components/student/report/DetailReport.vue, src/components/student/report/QuestionHtmlModal.vue
closes #92 
---
feat:평균 정답률 막대 그래프
---
---
---
---
=> feat:평균 정답률 막대 그래프

src/components/student/report/DetailReport.vue
closes #97 
---
detail report katex rendering error 수정
---
---
---
---
=> detail report katex rendering error 수정

src/components/student/report/BasicReport.vue, src/components/student/report/DetailReport.vue, src/components/student/report/MultiDatasetChartComponent.vue, src/services/detailReportPdfService.js, src/services/htmlToPdfService.js, src/services/simpleDetailReportPdfService.js, src/utils/pdftemplates/detailReportTemplate.js
closes #123 
---
feat:상세리포트 pdf파일 다운로드 구현
---
---
---
---
=> feat:상세리포트 pdf파일 다운로드 구현

src/components/student/class-room/composables/useClassWebSocket.js, src/components/student/class-room/liveExamManagement.vue, src/components/student/class-room/myClass.vue, src/router/index.js, src/services/websocket.js
closes #122 
---
실시간시험(학생, 선생님) 추가
---
---
---
---
=> 실시간시험(학생, 선생님) 추가

package-lock.json, package.json, src/components/student/class-room/BoxPlot.vue, src/components/student/class-room/StudentScore.vue, src/router/index.js, src/services/classApi.js
closes #120 
---
class 시험별 통계표 차트 화면 렌더링
---
---
---
---
=> class stats 통계표/차트 화면 렌더링

src/components/student/report/DetailReport.vue, src/components/student/report/MultiDatasetChartComponent.vue, src/services/htmlToPdfService.js
closes #125
---
fix:pdf 다운로드 용량 최적화
---
---
---
---
=> fix:pdf 다운로드 용량 최적화

src/components/student/class-room/BoxPlot.vue, src/components/student/class-room/StudentScore.vue, src/components/student/report/MultiDatasetChartComponent.vue
closes #133 
---
feat:Studentscore css 구현
---
---
---
---
=> feat:Studentscore css 구현

src/components/student/class-room/LiveExam.vue, src/components/student/class-room/LiveExamManagement.vue, src/components/student/class-room/LiveExamRoom.vue, src/components/student/class-room/composables/useClassWebSocket.js, src/components/student/class-room/myClass.vue, src/router/index.js, src/services/classApi.js, src/services/websocket.js
closes #143 
---
---
---
---
---
=> feat: 실시간 시험 관련 기능 추가

package.json
=> feat: hotfix

src/router/index.js, src/views/Login.vue
=> feat: findId
